services:
  web1:
    container_name: sdc-overview
    build: .
    depends_on :
      - "db"

  web2:
    container_name: sdc-overview
    build: .
    depends_on :
      - "db"

  web3:
    container_name: sdc-overview
    build: .
    depends_on :
      - "db"

  web4:
    container_name: sdc-overview
    build: .
    depends_on :
      - "db"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andychen
      POSTGRES_PASSWORD: 7798
      POSTGRES_DB: sdc

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on :
      - web1
      - web2
      - web3
      - web4