services:
  web1:
    depends on :
     - "db"
    container_name: sdc-overview
    build: .
    ports:
      - '2000:3000'

  web2:
    depends on :
     - "db"
    container_name: sdc-overview
    build: .
    ports:
    - '2001:3000'

  web3:
    depends on :
    - "db"
    container_name: sdc-overview
    build: .
    ports:
      - '2002:3000'

  web4:
    depends on :
     - "db"
    container_name: sdc-overview
    build: .
    ports:
      - '2003:3000'

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andychen
      POSTGRES_PASSWORD: 7798
      POSTGRES_DB: sdc

   nginx:
    depends on :
      - web1
      - web2
      - web3
      - web4
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
