services:
  web:
    depends on :
     - "db"
    container_name: sdc-overview
    build: .
    ports:
      - '2000:3000'
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andychen
      POSTGRES_PASSWORD: 7798
      POSTGRES_DB: sdc
=